#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaLeaderboardTab

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "CommonInput_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.ExecuteUbergraph_AthenaLeaderboardTab
// 0x0258 (0x0258 - 0x0000)
struct AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortLeaderboardContext*                CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanShowLeaderboards_ReturnValue;          // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortLeaderboardContext*                CallFunc_GetContext_ReturnValue_1;                 // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanShowGlobalLeaderboards_ReturnValue;    // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_3;                              // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_4;                              // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_5;                              // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate;              // 0x0034(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable_4;                              // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_6;                              // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_7;                              // 0x0046(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_5;                              // 0x0047(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_8;                              // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_9;                              // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4A[0x6];                                       // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortLeaderboardContext*                CallFunc_GetContext_ReturnValue_2;                 // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_6;                              // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanShowStats_ReturnValue;                 // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_10;                             // 0x005A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_11;                             // 0x005B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_7;                              // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x005D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_12;                             // 0x005E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_13;                             // 0x005F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_2;                           // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                K2Node_ComponentBoundEvent_ActiveWidget;           // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_ActiveWidgetIndex;      // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Value_1;                // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Value;                  // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_Event_Button;                               // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAthenaPlaylistLeaderboardData         K2Node_Event_PlaylistTabData_1;                    // 0x0088(0x0068)(ConstParm)
	bool                                          K2Node_Event_bWasSuccessful;                       // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortLeaderboardRowProxyInstance*       K2Node_Event_LocalUserRow;                         // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Event_QueryErrorStr;                        // 0x0100(0x0018)(ConstParm)
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0118(0x0018)()
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_3;                           // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_132[0x6];                                      // 0x0132(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaLeaderboardTabButton_C*          K2Node_DynamicCast_AsAthena_Leaderboard_Tab_Button; // 0x0138(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_14;                             // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_142[0x6];                                      // 0x0142(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAthenaPlaylistLeaderboardData         K2Node_Event_PlaylistTabData;                      // 0x0148(0x0068)(ConstParm)
	TDelegate<void(bool* bPassThrough)>           K2Node_CreateDelegate_OutputDelegate_1;            // 0x01B0(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(bool* bPassThrough)>           K2Node_CreateDelegate_OutputDelegate_2;            // 0x01C0(0x0010)(ZeroConstructor, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_15;                             // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue; // 0x01D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_8;                              // 0x01D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_16;                             // 0x01D3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_4;                           // 0x01D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D5[0x3];                                      // 0x01D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x01DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_5;                           // 0x01DD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01DE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x01DF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_6;                           // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SelectTabByID_ReturnValue;                // 0x01E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_17;                             // 0x01E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HandleBackAction_PassThrough;             // 0x01E3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_9;                              // 0x01E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ECommonInputType                              K2Node_CustomEvent_bNewInputType;                  // 0x01E5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E6[0x2];                                      // 0x01E6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortLeaderboardContext*                CallFunc_GetContext_ReturnValue_3;                 // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanShowLeaderboards_ReturnValue_1;        // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F1[0x7];                                      // 0x01F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortRuntimeOptions*                    CallFunc_GetRuntimeOptions_ReturnValue;            // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_7;                           // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_8;                           // 0x0201(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_202[0x6];                                      // 0x0202(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortFrontEndContext*                   CallFunc_GetContext_ReturnValue_4;                 // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0210(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_214[0x4];                                      // 0x0214(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonLegacy*                    K2Node_ComponentBoundEvent_Button_1;               // 0x0218(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonLegacy*                    K2Node_ComponentBoundEvent_Button;                 // 0x0220(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_ComponentBoundEvent_TabId_1;                // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_TabButton_1;            // 0x0230(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0238(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_ComponentBoundEvent_TabId;                  // 0x023C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_244[0x4];                                      // 0x0244(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_TabButton;              // 0x0248(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default_9;                           // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Remove_ReturnValue;                   // 0x0254(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab");
static_assert(sizeof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab) == 0x000258, "Wrong size on AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, EntryPoint) == 0x000000, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::EntryPoint' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable) == 0x000004, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_1) == 0x000005, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable) == 0x000006, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_1) == 0x000007, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_2) == 0x000010, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_CanShowLeaderboards_ReturnValue) == 0x000011, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_CanShowLeaderboards_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_2) == 0x000012, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_3) == 0x000013, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetContext_ReturnValue_1) == 0x000018, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetContext_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_CanShowGlobalLeaderboards_ReturnValue) == 0x000020, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_CanShowGlobalLeaderboards_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_3) == 0x000021, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_4) == 0x000022, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_5) == 0x000023, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_5' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000028, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default) == 0x000030, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_CreateDelegate_OutputDelegate) == 0x000034, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_4) == 0x000044, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_6) == 0x000045, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_6' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_7) == 0x000046, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_7' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_5) == 0x000047, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_5' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_8) == 0x000048, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_8' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_9) == 0x000049, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_9' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetContext_ReturnValue_2) == 0x000050, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetContext_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_6) == 0x000058, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_6' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_CanShowStats_ReturnValue) == 0x000059, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_CanShowStats_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_10) == 0x00005A, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_10' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_11) == 0x00005B, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_11' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_7) == 0x00005C, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_7' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_1) == 0x00005D, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_12) == 0x00005E, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_12' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_13) == 0x00005F, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_13' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_2) == 0x000060, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_ActiveWidget) == 0x000068, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_ActiveWidget' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_ActiveWidgetIndex) == 0x000070, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_ActiveWidgetIndex' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_Value_1) == 0x000074, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_Value_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_Value) == 0x000078, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_Value' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_Button) == 0x000080, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_Button' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_PlaylistTabData_1) == 0x000088, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_PlaylistTabData_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_bWasSuccessful) == 0x0000F0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_bWasSuccessful' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_LocalUserRow) == 0x0000F8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_LocalUserRow' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_QueryErrorStr) == 0x000100, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_QueryErrorStr' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_TextToUpper_ReturnValue) == 0x000118, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_TextToUpper_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000130, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_3) == 0x000131, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_DynamicCast_AsAthena_Leaderboard_Tab_Button) == 0x000138, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_DynamicCast_AsAthena_Leaderboard_Tab_Button' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_DynamicCast_bSuccess) == 0x000140, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_14) == 0x000141, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_14' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_PlaylistTabData) == 0x000148, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_PlaylistTabData' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_CreateDelegate_OutputDelegate_1) == 0x0001B0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_CreateDelegate_OutputDelegate_2) == 0x0001C0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_15) == 0x0001D0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_15' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue) == 0x0001D1, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_8) == 0x0001D2, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_8' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_16) == 0x0001D3, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_16' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_4) == 0x0001D4, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_Array_Length_ReturnValue) == 0x0001D8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_Greater_IntInt_ReturnValue) == 0x0001DC, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_5) == 0x0001DD, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_5' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_BooleanAND_ReturnValue) == 0x0001DE, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_BooleanAND_ReturnValue_1) == 0x0001DF, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_6) == 0x0001E0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_6' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_SelectTabByID_ReturnValue) == 0x0001E1, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_SelectTabByID_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_17) == 0x0001E2, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_17' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_HandleBackAction_PassThrough) == 0x0001E3, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_HandleBackAction_PassThrough' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_9) == 0x0001E4, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_9' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_CustomEvent_bNewInputType) == 0x0001E5, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_CustomEvent_bNewInputType' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetContext_ReturnValue_3) == 0x0001E8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetContext_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_CanShowLeaderboards_ReturnValue_1) == 0x0001F0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_CanShowLeaderboards_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetRuntimeOptions_ReturnValue) == 0x0001F8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetRuntimeOptions_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_7) == 0x000200, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_7' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_8) == 0x000201, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_8' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetContext_ReturnValue_4) == 0x000208, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetContext_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_int_Variable) == 0x000210, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_Button_1) == 0x000218, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_Button_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_Button) == 0x000220, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_TabId_1) == 0x000228, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_TabId_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_TabButton_1) == 0x000230, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_TabButton_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_int_Variable_1) == 0x000238, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_TabId) == 0x00023C, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_TabId' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_TabButton) == 0x000248, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_TabButton' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_9) == 0x000250, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_9' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_Map_Remove_ReturnValue) == 0x000254, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_Map_Remove_ReturnValue' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_1_OnTabButtonRemoval__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_1_OnTabButtonRemoval__DelegateSignature final
{
public:
	class FName                                   TabId;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      TabButton;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_1_OnTabButtonRemoval__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_1_OnTabButtonRemoval__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_1_OnTabButtonRemoval__DelegateSignature) == 0x000010, "Wrong size on AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_1_OnTabButtonRemoval__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_1_OnTabButtonRemoval__DelegateSignature, TabId) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_1_OnTabButtonRemoval__DelegateSignature::TabId' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_1_OnTabButtonRemoval__DelegateSignature, TabButton) == 0x000008, "Member 'AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_1_OnTabButtonRemoval__DelegateSignature::TabButton' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_0_OnTabButtonCreation__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_0_OnTabButtonCreation__DelegateSignature final
{
public:
	class FName                                   TabId;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      TabButton;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_0_OnTabButtonCreation__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_0_OnTabButtonCreation__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_0_OnTabButtonCreation__DelegateSignature) == 0x000010, "Wrong size on AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_0_OnTabButtonCreation__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_0_OnTabButtonCreation__DelegateSignature, TabId) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_0_OnTabButtonCreation__DelegateSignature::TabId' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_0_OnTabButtonCreation__DelegateSignature, TabButton) == 0x000008, "Member 'AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_0_OnTabButtonCreation__DelegateSignature::TabButton' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__CloseButton_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__CloseButton_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButtonLegacy*                    Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__CloseButton_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__CloseButton_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__CloseButton_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on AthenaLeaderboardTab_C_BndEvt__CloseButton_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__CloseButton_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__CloseButton_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__CloseButton_2_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__CloseButton_2_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButtonLegacy*                    Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__CloseButton_2_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__CloseButton_2_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__CloseButton_2_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on AthenaLeaderboardTab_C_BndEvt__CloseButton_2_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__CloseButton_2_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__CloseButton_2_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnInputMethodChanged_Event_0
// 0x0001 (0x0001 - 0x0000)
struct AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0 final
{
public:
	ECommonInputType                              bNewInputType;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0) == 0x000001, "Wrong alignment on AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0");
static_assert(sizeof(AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0) == 0x000001, "Wrong size on AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0");
static_assert(offsetof(AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0, bNewInputType) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0::bNewInputType' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnUpdateListHeader
// 0x0068 (0x0068 - 0x0000)
struct AthenaLeaderboardTab_C_OnUpdateListHeader final
{
public:
	struct FAthenaPlaylistLeaderboardData         PlaylistTabData;                                   // 0x0000(0x0068)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnUpdateListHeader) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnUpdateListHeader");
static_assert(sizeof(AthenaLeaderboardTab_C_OnUpdateListHeader) == 0x000068, "Wrong size on AthenaLeaderboardTab_C_OnUpdateListHeader");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateListHeader, PlaylistTabData) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnUpdateListHeader::PlaylistTabData' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnUpdateLeaderboardListUI
// 0x0028 (0x0028 - 0x0000)
struct AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI final
{
public:
	bool                                          bWasSuccessful;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortLeaderboardRowProxyInstance*       LocalUserRow_0;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   QueryErrorStr;                                     // 0x0010(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI");
static_assert(sizeof(AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI) == 0x000028, "Wrong size on AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI, bWasSuccessful) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI::bWasSuccessful' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI, LocalUserRow_0) == 0x000008, "Member 'AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI::LocalUserRow_0' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI, QueryErrorStr) == 0x000010, "Member 'AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI::QueryErrorStr' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnUpdateTabButtonText
// 0x0070 (0x0070 - 0x0000)
struct AthenaLeaderboardTab_C_OnUpdateTabButtonText final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAthenaPlaylistLeaderboardData         PlaylistTabData;                                   // 0x0008(0x0068)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnUpdateTabButtonText) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnUpdateTabButtonText");
static_assert(sizeof(AthenaLeaderboardTab_C_OnUpdateTabButtonText) == 0x000070, "Wrong size on AthenaLeaderboardTab_C_OnUpdateTabButtonText");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateTabButtonText, Button) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnUpdateTabButtonText::Button' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateTabButtonText, PlaylistTabData) == 0x000008, "Member 'AthenaLeaderboardTab_C_OnUpdateTabButtonText::PlaylistTabData' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature final
{
public:
	int32                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature) == 0x000004, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature) == 0x000004, "Wrong size on AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature, Value) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature::Value' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature final
{
public:
	int32                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature) == 0x000004, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature) == 0x000004, "Wrong size on AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature, Value) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature::Value' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature final
{
public:
	class UWidget*                                ActiveWidget;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ActiveWidgetIndex;                                 // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature) == 0x000010, "Wrong size on AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature, ActiveWidget) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature::ActiveWidget' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature, ActiveWidgetIndex) == 0x000008, "Member 'AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature::ActiveWidgetIndex' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnPlaylistChangeGamepad
// 0x0028 (0x0028 - 0x0000)
struct AthenaLeaderboardTab_C_OnPlaylistChangeGamepad final
{
public:
	bool                                          bCommitted;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaRotator_C*                       K2Node_DynamicCast_AsAthena_Rotator;               // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnPlaylistChangeGamepad");
static_assert(sizeof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad) == 0x000028, "Wrong size on AthenaLeaderboardTab_C_OnPlaylistChangeGamepad");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, bCommitted) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::bCommitted' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, CallFunc_GetCurrentInputType_ReturnValue) == 0x000010, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000011, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, K2Node_DynamicCast_AsAthena_Rotator) == 0x000018, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::K2Node_DynamicCast_AsAthena_Rotator' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnFriendTypeChangeGamepad
// 0x0028 (0x0028 - 0x0000)
struct AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad final
{
public:
	bool                                          bCommitted;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaRotator_C*                       K2Node_DynamicCast_AsAthena_Rotator;               // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad");
static_assert(sizeof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad) == 0x000028, "Wrong size on AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, bCommitted) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::bCommitted' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, CallFunc_GetCurrentInputType_ReturnValue) == 0x000010, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, K2Node_DynamicCast_AsAthena_Rotator) == 0x000018, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::K2Node_DynamicCast_AsAthena_Rotator' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000021, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnQueryStateChanged
// 0x0020 (0x0020 - 0x0000)
struct AthenaLeaderboardTab_C_OnQueryStateChanged final
{
public:
	bool                                          bQueryInProgress;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue; // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3[0x1];                                        // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnQueryStateChanged) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnQueryStateChanged");
static_assert(sizeof(AthenaLeaderboardTab_C_OnQueryStateChanged) == 0x000020, "Wrong size on AthenaLeaderboardTab_C_OnQueryStateChanged");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, bQueryInProgress) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::bQueryInProgress' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, CallFunc_Not_PreBool_ReturnValue) == 0x000001, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue) == 0x000002, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, CallFunc_BooleanAND_ReturnValue) == 0x000014, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000018, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.ToggleDisabledTabVisuals
// 0x0002 (0x0002 - 0x0000)
struct AthenaLeaderboardTab_C_ToggleDisabledTabVisuals final
{
public:
	bool                                          bShouldBeDisabled;                                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_ToggleDisabledTabVisuals) == 0x000001, "Wrong alignment on AthenaLeaderboardTab_C_ToggleDisabledTabVisuals");
static_assert(sizeof(AthenaLeaderboardTab_C_ToggleDisabledTabVisuals) == 0x000002, "Wrong size on AthenaLeaderboardTab_C_ToggleDisabledTabVisuals");
static_assert(offsetof(AthenaLeaderboardTab_C_ToggleDisabledTabVisuals, bShouldBeDisabled) == 0x000000, "Member 'AthenaLeaderboardTab_C_ToggleDisabledTabVisuals::bShouldBeDisabled' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ToggleDisabledTabVisuals, CallFunc_Not_PreBool_ReturnValue) == 0x000001, "Member 'AthenaLeaderboardTab_C_ToggleDisabledTabVisuals::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.HandleBackAction
// 0x0001 (0x0001 - 0x0000)
struct AthenaLeaderboardTab_C_HandleBackAction final
{
public:
	bool                                          PassThrough;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_HandleBackAction) == 0x000001, "Wrong alignment on AthenaLeaderboardTab_C_HandleBackAction");
static_assert(sizeof(AthenaLeaderboardTab_C_HandleBackAction) == 0x000001, "Wrong size on AthenaLeaderboardTab_C_HandleBackAction");
static_assert(offsetof(AthenaLeaderboardTab_C_HandleBackAction, PassThrough) == 0x000000, "Member 'AthenaLeaderboardTab_C_HandleBackAction::PassThrough' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.Init Back Action
// 0x0020 (0x0020 - 0x0000)
struct AthenaLeaderboardTab_C_Init_Back_Action final
{
public:
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool* bPassThrough)>           K2Node_CreateDelegate_OutputDelegate;              // 0x000C(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasInputActionHandler_ReturnValue;        // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_Init_Back_Action) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_Init_Back_Action");
static_assert(sizeof(AthenaLeaderboardTab_C_Init_Back_Action) == 0x000020, "Wrong size on AthenaLeaderboardTab_C_Init_Back_Action");
static_assert(offsetof(AthenaLeaderboardTab_C_Init_Back_Action, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000000, "Member 'AthenaLeaderboardTab_C_Init_Back_Action::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_Init_Back_Action, CallFunc_GetCurrentInputType_ReturnValue) == 0x000008, "Member 'AthenaLeaderboardTab_C_Init_Back_Action::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_Init_Back_Action, K2Node_CreateDelegate_OutputDelegate) == 0x00000C, "Member 'AthenaLeaderboardTab_C_Init_Back_Action::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_Init_Back_Action, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00001C, "Member 'AthenaLeaderboardTab_C_Init_Back_Action::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_Init_Back_Action, CallFunc_HasInputActionHandler_ReturnValue) == 0x00001D, "Member 'AthenaLeaderboardTab_C_Init_Back_Action::CallFunc_HasInputActionHandler_ReturnValue' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.UpdateRotatorsForInput
// 0x0020 (0x0020 - 0x0000)
struct AthenaLeaderboardTab_C_UpdateRotatorsForInput final
{
public:
	class UAthenaRotator_C*                       K2Node_DynamicCast_AsAthena_Rotator;               // 0x0000(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaRotator_C*                       K2Node_DynamicCast_AsAthena_Rotator_1;             // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsUsingTouch_ReturnValue;                 // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_UpdateRotatorsForInput) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_UpdateRotatorsForInput");
static_assert(sizeof(AthenaLeaderboardTab_C_UpdateRotatorsForInput) == 0x000020, "Wrong size on AthenaLeaderboardTab_C_UpdateRotatorsForInput");
static_assert(offsetof(AthenaLeaderboardTab_C_UpdateRotatorsForInput, K2Node_DynamicCast_AsAthena_Rotator) == 0x000000, "Member 'AthenaLeaderboardTab_C_UpdateRotatorsForInput::K2Node_DynamicCast_AsAthena_Rotator' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_UpdateRotatorsForInput, K2Node_DynamicCast_bSuccess) == 0x000008, "Member 'AthenaLeaderboardTab_C_UpdateRotatorsForInput::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_UpdateRotatorsForInput, K2Node_DynamicCast_AsAthena_Rotator_1) == 0x000010, "Member 'AthenaLeaderboardTab_C_UpdateRotatorsForInput::K2Node_DynamicCast_AsAthena_Rotator_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_UpdateRotatorsForInput, K2Node_DynamicCast_bSuccess_1) == 0x000018, "Member 'AthenaLeaderboardTab_C_UpdateRotatorsForInput::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_UpdateRotatorsForInput, CallFunc_IsUsingTouch_ReturnValue) == 0x000019, "Member 'AthenaLeaderboardTab_C_UpdateRotatorsForInput::CallFunc_IsUsingTouch_ReturnValue' has a wrong offset!");

}

