#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_AnimBP_HightowerRadish

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass B_AnimBP_HightowerRadish.B_AnimBP_HightowerRadish_C
// 0x4E00 (0x5520 - 0x0720)
class UB_AnimBP_HightowerRadish_C final : public UFortPetAnimInstance_HighTowerRadish
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0720(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0728(0x0030)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x0758(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_4;                        // 0x0778(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_3;                        // 0x0880(0x0108)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_52;                 // 0x0988(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_51;                 // 0x09B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_50;                 // 0x09D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_49;                 // 0x0A00(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_48;                 // 0x0A28(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_47;                 // 0x0A50(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_46;                 // 0x0A78(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_45;                 // 0x0AA0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_44;                 // 0x0AC8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_43;                 // 0x0AF0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_42;                   // 0x0B18(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_33;                      // 0x0B98(0x0030)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_7;                  // 0x0BC8(0x00E8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_41;                   // 0x0CB0(0x0080)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_11;                    // 0x0D30(0x00C8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_32;                      // 0x0DF8(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_42;                 // 0x0E28(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_40;                   // 0x0E50(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_31;                      // 0x0ED0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_39;                   // 0x0F00(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_30;                      // 0x0F80(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_7;                      // 0x0FB0(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_29;                      // 0x1060(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_41;                 // 0x1090(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_40;                 // 0x10B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39;                 // 0x10E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38;                 // 0x1108(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37;                 // 0x1130(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36;                 // 0x1158(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x1180(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x11A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x11D0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_38;                   // 0x11F8(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_28;                      // 0x1278(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_37;                   // 0x12A8(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_27;                      // 0x1328(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_36;                   // 0x1358(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_26;                      // 0x13D8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_35;                   // 0x1408(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_25;                      // 0x1488(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_34;                   // 0x14B8(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_24;                      // 0x1538(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_33;                   // 0x1568(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_23;                      // 0x15E8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_32;                   // 0x1618(0x0080)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_10;                    // 0x1698(0x00C8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_6;                  // 0x1760(0x00E8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_22;                      // 0x1848(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_6;                      // 0x1878(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x1928(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_31;                   // 0x1958(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x19D8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_30;                   // 0x1A08(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x1A88(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x1AB8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x1AE0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x1B08(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x1B30(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x1B58(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x1B80(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x1BA8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x1BD0(0x0028)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x1BF8(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_29;                   // 0x1CC0(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_28;                   // 0x1D40(0x0080)()
	struct FAnimNode_ApplyMeshSpaceAdditive       AnimGraphNode_ApplyMeshSpaceAdditive_3;            // 0x1DC0(0x00D0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_6;                   // 0x1E90(0x00A0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_27;                   // 0x1F30(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_26;                   // 0x1FB0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x2030(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x2060(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x2088(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x20B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x20D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x2100(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x2128(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x2150(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x2178(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x21A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x21C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x21F0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_25;                   // 0x2218(0x0080)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_9;                     // 0x2298(0x00C8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_5;                  // 0x2360(0x00E8)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_8;                     // 0x2448(0x00C8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_4;                  // 0x2510(0x00E8)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt;                      // 0x25F8(0x00A0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_24;                   // 0x2698(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x2718(0x0030)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_7;                     // 0x2748(0x00C8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_3;                  // 0x2810(0x00E8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_23;                   // 0x28F8(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x2978(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_22;                   // 0x29A8(0x0080)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_6;                     // 0x2A28(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_21;                   // 0x2AF0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x2B70(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_20;                   // 0x2BA0(0x0080)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_5;                   // 0x2C20(0x00A0)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_5;                     // 0x2CC0(0x00C8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_2;                  // 0x2D88(0x00E8)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_4;                     // 0x2E70(0x00C8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x2F38(0x00E8)()
	struct FAnimNode_ApplyMeshSpaceAdditive       AnimGraphNode_ApplyMeshSpaceAdditive_2;            // 0x3020(0x00D0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_19;                   // 0x30F0(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_18;                   // 0x3170(0x0080)()
	struct FAnimNode_RefPose                      AnimGraphNode_IdentityPose;                        // 0x31F0(0x0018)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17;                   // 0x3208(0x0080)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_4;                   // 0x3288(0x00A0)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_3;                     // 0x3328(0x00C8)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x33F0(0x00A0)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_2;                     // 0x3490(0x00C8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x3558(0x00E8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x3640(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x36C0(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_5;                      // 0x36F0(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x37A0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x37D0(0x0080)()
	struct FAnimNode_ApplyMeshSpaceAdditive       AnimGraphNode_ApplyMeshSpaceAdditive_1;            // 0x3850(0x00D0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x3920(0x0080)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x39A0(0x00A0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x3A40(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x3AC0(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x3AF0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x3B18(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x3B40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x3B68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x3B90(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x3BB8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x3BE0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x3C60(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x3C90(0x0080)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_1;                     // 0x3D10(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x3DD8(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x3E58(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x3E88(0x0080)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x3F08(0x00A0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x3FA8(0x0080)()
	struct FAnimNode_ApplyMeshSpaceAdditive       AnimGraphNode_ApplyMeshSpaceAdditive;              // 0x4028(0x00D0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x40F8(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x4178(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_4;                      // 0x41A8(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x4258(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3;                      // 0x4288(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x4338(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x4368(0x00B0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_1;                          // 0x4418(0x00F0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x4508(0x0020)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x4528(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x4680(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x46A8(0x0020)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x46C8(0x00A0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x4768(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x4790(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x47B8(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x4838(0x0080)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x48B8(0x00C8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x4980(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x49B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x49D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x4A00(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x4A28(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x4A50(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x4A78(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x4AA0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x4B20(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x4B50(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x4BD0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x4C00(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x4C80(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x4CB0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x4D30(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x4D60(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x4DE0(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x4E10(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x4EC0(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x4EF0(0x00B0)()
	struct FAnimNode_LegIK                        AnimGraphNode_LegIK;                               // 0x4FA0(0x00F8)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x5098(0x0108)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone;                            // 0x51A0(0x00F0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x5290(0x0020)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x52B0(0x0048)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x52F8(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x5400(0x0108)()
	bool                                          bStoppedMovingOrMeleeForLongEnoughTime;            // 0x5508(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bSharpDirectionChange;                             // 0x5509(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bHighTowerRadish_LobbySkyDive_Diving;              // 0x550A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bHighTowerRadish_LobbySkyDive_Gliding;             // 0x550B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bFrontEndIdleTransition;                           // 0x550C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bIsPlayingMeleeAnimLastTick;                       // 0x550D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_550E[0x2];                                     // 0x550E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         RandomLocomotionBreak;                             // 0x5510(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bAllowRandomLocomotionBreak;                       // 0x5514(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bHasTargettedInLastNSeconds;                       // 0x5515(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5516[0x2];                                     // 0x5516(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         IsDBNOCarriedAlpha;                                // 0x5518(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_B_AnimBP_HightowerRadish_AnimGraphNode_ModifyBone_441853F14CF887B70AF6429E488FED76();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void HighTowerRadish_Lobby_SkyDive_Diving();
	void HighTowerRadish_Lobby_SkyDive_Gliding();
	void AnimNotify_RandomIdlePick();
	void AnimNotify_BwdToFwd_Entered();
	void AnimNotify_FwdToBwd_Entered();
	void AnimNotify_TriggerRandomizer();
	void AnimNotify_MoveLoopRandomEntered();
	void OnEnteredVehicle();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_B_AnimBP_HightowerRadish_AnimGraphNode_TransitionResult_7063B86B4BA21930F893DBA578CF6DAD();
	void OnExitedVehicle();
	void ExecuteUbergraph_B_AnimBP_HightowerRadish(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_AnimBP_HightowerRadish_C">();
	}
	static class UB_AnimBP_HightowerRadish_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UB_AnimBP_HightowerRadish_C>();
	}
};
static_assert(alignof(UB_AnimBP_HightowerRadish_C) == 0x000010, "Wrong alignment on UB_AnimBP_HightowerRadish_C");
static_assert(sizeof(UB_AnimBP_HightowerRadish_C) == 0x005520, "Wrong size on UB_AnimBP_HightowerRadish_C");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, UberGraphFrame) == 0x000720, "Member 'UB_AnimBP_HightowerRadish_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_Root) == 0x000728, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_LocalToComponentSpace_1) == 0x000758, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_LocalToComponentSpace_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ModifyBone_4) == 0x000778, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ModifyBone_4' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ModifyBone_3) == 0x000880, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ModifyBone_3' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_52) == 0x000988, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_52' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_51) == 0x0009B0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_51' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_50) == 0x0009D8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_50' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_49) == 0x000A00, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_49' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_48) == 0x000A28, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_48' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_47) == 0x000A50, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_47' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_46) == 0x000A78, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_46' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_45) == 0x000AA0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_45' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_44) == 0x000AC8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_44' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_43) == 0x000AF0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_43' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_42) == 0x000B18, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_42' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_33) == 0x000B98, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_33' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendSpacePlayer_7) == 0x000BC8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendSpacePlayer_7' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_41) == 0x000CB0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_41' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_11) == 0x000D30, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_11' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_32) == 0x000DF8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_32' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_42) == 0x000E28, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_42' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_40) == 0x000E50, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_40' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_31) == 0x000ED0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_31' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_39) == 0x000F00, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_39' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_30) == 0x000F80, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_30' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateMachine_7) == 0x000FB0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateMachine_7' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_29) == 0x001060, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_29' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_41) == 0x001090, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_41' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_40) == 0x0010B8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_40' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_39) == 0x0010E0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_39' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_38) == 0x001108, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_38' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_37) == 0x001130, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_37' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_36) == 0x001158, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_36' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_35) == 0x001180, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_35' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_34) == 0x0011A8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_34' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_33) == 0x0011D0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_33' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_38) == 0x0011F8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_38' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_28) == 0x001278, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_28' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_37) == 0x0012A8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_37' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_27) == 0x001328, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_27' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_36) == 0x001358, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_36' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_26) == 0x0013D8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_26' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_35) == 0x001408, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_35' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_25) == 0x001488, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_25' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_34) == 0x0014B8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_34' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_24) == 0x001538, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_24' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_33) == 0x001568, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_33' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_23) == 0x0015E8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_23' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_32) == 0x001618, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_32' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_10) == 0x001698, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_10' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendSpacePlayer_6) == 0x001760, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendSpacePlayer_6' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_22) == 0x001848, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_22' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateMachine_6) == 0x001878, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateMachine_6' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_21) == 0x001928, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_21' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_31) == 0x001958, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_31' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_20) == 0x0019D8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_20' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_30) == 0x001A08, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_30' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_19) == 0x001A88, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_19' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_32) == 0x001AB8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_32' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_31) == 0x001AE0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_31' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_30) == 0x001B08, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_30' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_29) == 0x001B30, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_29' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_28) == 0x001B58, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_28' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_27) == 0x001B80, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_27' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_26) == 0x001BA8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_26' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_25) == 0x001BD0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_25' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TwoWayBlend) == 0x001BF8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_29) == 0x001CC0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_29' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_28) == 0x001D40, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_28' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyMeshSpaceAdditive_3) == 0x001DC0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyMeshSpaceAdditive_3' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendListByBool_6) == 0x001E90, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendListByBool_6' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_27) == 0x001F30, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_27' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_26) == 0x001FB0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_26' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_18) == 0x002030, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_18' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_24) == 0x002060, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_24' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_23) == 0x002088, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_23' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_22) == 0x0020B0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_22' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_21) == 0x0020D8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_21' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_20) == 0x002100, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_20' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_19) == 0x002128, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_19' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_18) == 0x002150, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_18' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_17) == 0x002178, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_17' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_16) == 0x0021A0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_16' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_15) == 0x0021C8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_15' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_14) == 0x0021F0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_14' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_25) == 0x002218, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_25' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_9) == 0x002298, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_9' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendSpacePlayer_5) == 0x002360, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendSpacePlayer_5' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_8) == 0x002448, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_8' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendSpacePlayer_4) == 0x002510, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendSpacePlayer_4' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendListByInt) == 0x0025F8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendListByInt' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_24) == 0x002698, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_24' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_17) == 0x002718, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_17' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_7) == 0x002748, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_7' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendSpacePlayer_3) == 0x002810, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendSpacePlayer_3' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_23) == 0x0028F8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_23' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_16) == 0x002978, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_16' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_22) == 0x0029A8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_22' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_6) == 0x002A28, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_6' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_21) == 0x002AF0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_21' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_15) == 0x002B70, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_15' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_20) == 0x002BA0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_20' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendListByBool_5) == 0x002C20, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendListByBool_5' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_5) == 0x002CC0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_5' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendSpacePlayer_2) == 0x002D88, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendSpacePlayer_2' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_4) == 0x002E70, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_4' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendSpacePlayer_1) == 0x002F38, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendSpacePlayer_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyMeshSpaceAdditive_2) == 0x003020, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyMeshSpaceAdditive_2' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_19) == 0x0030F0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_19' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_18) == 0x003170, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_18' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_IdentityPose) == 0x0031F0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_IdentityPose' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_17) == 0x003208, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_17' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendListByBool_4) == 0x003288, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendListByBool_4' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_3) == 0x003328, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_3' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendListByBool_3) == 0x0033F0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendListByBool_3' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_2) == 0x003490, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_2' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendSpacePlayer) == 0x003558, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_16) == 0x003640, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_16' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_14) == 0x0036C0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_14' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateMachine_5) == 0x0036F0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateMachine_5' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_13) == 0x0037A0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_13' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_15) == 0x0037D0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_15' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyMeshSpaceAdditive_1) == 0x003850, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyMeshSpaceAdditive_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_14) == 0x003920, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_14' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendListByBool_2) == 0x0039A0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendListByBool_2' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_13) == 0x003A40, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_13' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_12) == 0x003AC0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_12' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_13) == 0x003AF0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_13' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_12) == 0x003B18, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_11) == 0x003B40, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_10) == 0x003B68, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_9) == 0x003B90, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_8) == 0x003BB8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_12) == 0x003BE0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_11) == 0x003C60, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_11' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_11) == 0x003C90, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive_1) == 0x003D10, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_10) == 0x003DD8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_10) == 0x003E58, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_10' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_9) == 0x003E88, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendListByBool_1) == 0x003F08, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_8) == 0x003FA8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyMeshSpaceAdditive) == 0x004028, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyMeshSpaceAdditive' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_7) == 0x0040F8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_9) == 0x004178, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_9' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateMachine_4) == 0x0041A8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateMachine_4' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_8) == 0x004258, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_8' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateMachine_3) == 0x004288, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateMachine_3' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_7) == 0x004338, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_7' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateMachine_2) == 0x004368, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateMachine_2' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_CopyBone_1) == 0x004418, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_CopyBone_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ComponentToLocalSpace_1) == 0x004508, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ComponentToLocalSpace_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SaveCachedPose) == 0x004528, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_UseCachedPose) == 0x004680, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_LocalToComponentSpace) == 0x0046A8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_BlendListByBool) == 0x0046C8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_7) == 0x004768, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_6) == 0x004790, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_6) == 0x0047B8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_5) == 0x004838, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ApplyAdditive) == 0x0048B8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ApplyAdditive' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_6) == 0x004980, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_5) == 0x0049B0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_4) == 0x0049D8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_3) == 0x004A00, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_2) == 0x004A28, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult_1) == 0x004A50, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_TransitionResult) == 0x004A78, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_4) == 0x004AA0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_5) == 0x004B20, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_3) == 0x004B50, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_4) == 0x004BD0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_2) == 0x004C00, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_3) == 0x004C80, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer_1) == 0x004CB0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_2) == 0x004D30, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_SequencePlayer) == 0x004D60, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult_1) == 0x004DE0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateMachine_1) == 0x004E10, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateResult) == 0x004EC0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_StateMachine) == 0x004EF0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_LegIK) == 0x004FA0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_LegIK' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ModifyBone_2) == 0x005098, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ModifyBone_2' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_CopyBone) == 0x0051A0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_CopyBone' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ComponentToLocalSpace) == 0x005290, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_Slot) == 0x0052B0, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ModifyBone_1) == 0x0052F8, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ModifyBone_1' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, AnimGraphNode_ModifyBone) == 0x005400, "Member 'UB_AnimBP_HightowerRadish_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, bStoppedMovingOrMeleeForLongEnoughTime) == 0x005508, "Member 'UB_AnimBP_HightowerRadish_C::bStoppedMovingOrMeleeForLongEnoughTime' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, bSharpDirectionChange) == 0x005509, "Member 'UB_AnimBP_HightowerRadish_C::bSharpDirectionChange' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, bHighTowerRadish_LobbySkyDive_Diving) == 0x00550A, "Member 'UB_AnimBP_HightowerRadish_C::bHighTowerRadish_LobbySkyDive_Diving' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, bHighTowerRadish_LobbySkyDive_Gliding) == 0x00550B, "Member 'UB_AnimBP_HightowerRadish_C::bHighTowerRadish_LobbySkyDive_Gliding' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, bFrontEndIdleTransition) == 0x00550C, "Member 'UB_AnimBP_HightowerRadish_C::bFrontEndIdleTransition' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, bIsPlayingMeleeAnimLastTick) == 0x00550D, "Member 'UB_AnimBP_HightowerRadish_C::bIsPlayingMeleeAnimLastTick' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, RandomLocomotionBreak) == 0x005510, "Member 'UB_AnimBP_HightowerRadish_C::RandomLocomotionBreak' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, bAllowRandomLocomotionBreak) == 0x005514, "Member 'UB_AnimBP_HightowerRadish_C::bAllowRandomLocomotionBreak' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, bHasTargettedInLastNSeconds) == 0x005515, "Member 'UB_AnimBP_HightowerRadish_C::bHasTargettedInLastNSeconds' has a wrong offset!");
static_assert(offsetof(UB_AnimBP_HightowerRadish_C, IsDBNOCarriedAlpha) == 0x005518, "Member 'UB_AnimBP_HightowerRadish_C::IsDBNOCarriedAlpha' has a wrong offset!");

}

