#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_BuriedChest_Spawner_Parent

#include "Basic.hpp"

#include "B_Athena_BuriedChest_Spawner_Parent_classes.hpp"
#include "B_Athena_BuriedChest_Spawner_Parent_parameters.hpp"


namespace SDK
{

// Function B_Athena_BuriedChest_Spawner_Parent.B_Athena_BuriedChest_Spawner_Parent_C.ExecuteUbergraph_B_Athena_BuriedChest_Spawner_Parent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_BuriedChest_Spawner_Parent_C::ExecuteUbergraph_B_Athena_BuriedChest_Spawner_Parent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_BuriedChest_Spawner_Parent_C", "ExecuteUbergraph_B_Athena_BuriedChest_Spawner_Parent");

	Params::B_Athena_BuriedChest_Spawner_Parent_C_ExecuteUbergraph_B_Athena_BuriedChest_Spawner_Parent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_BuriedChest_Spawner_Parent.B_Athena_BuriedChest_Spawner_Parent_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_Athena_BuriedChest_Spawner_Parent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_BuriedChest_Spawner_Parent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_BuriedChest_Spawner_Parent.B_Athena_BuriedChest_Spawner_Parent_C.EQSFinished
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UEnvQueryInstanceBlueprintWrapper*QueryInstance                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEnvQueryStatus                         QueryStatus                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_BuriedChest_Spawner_Parent_C::EQSFinished(class UEnvQueryInstanceBlueprintWrapper* QueryInstance, EEnvQueryStatus QueryStatus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_BuriedChest_Spawner_Parent_C", "EQSFinished");

	Params::B_Athena_BuriedChest_Spawner_Parent_C_EQSFinished Parms{};

	Parms.QueryInstance = QueryInstance;
	Parms.QueryStatus = QueryStatus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_BuriedChest_Spawner_Parent.B_Athena_BuriedChest_Spawner_Parent_C.OnReady_15E7642D436E49800BF6F09D6BBB7637
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortGameStateAthena*             GameState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortPlaylist*                    Playlist                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            PlaylistContextTags                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void AB_Athena_BuriedChest_Spawner_Parent_C::OnReady_15E7642D436E49800BF6F09D6BBB7637(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_BuriedChest_Spawner_Parent_C", "OnReady_15E7642D436E49800BF6F09D6BBB7637");

	Params::B_Athena_BuriedChest_Spawner_Parent_C_OnReady_15E7642D436E49800BF6F09D6BBB7637 Parms{};

	Parms.GameState = GameState;
	Parms.Playlist = Playlist;
	Parms.PlaylistContextTags = std::move(PlaylistContextTags);

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_BuriedChest_Spawner_Parent.B_Athena_BuriedChest_Spawner_Parent_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AB_Athena_BuriedChest_Spawner_Parent_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_BuriedChest_Spawner_Parent_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_BuriedChest_Spawner_Parent.B_Athena_BuriedChest_Spawner_Parent_C.CheckForSpawnRate
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool AB_Athena_BuriedChest_Spawner_Parent_C::CheckForSpawnRate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_BuriedChest_Spawner_Parent_C", "CheckForSpawnRate");

	Params::B_Athena_BuriedChest_Spawner_Parent_C_CheckForSpawnRate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function B_Athena_BuriedChest_Spawner_Parent.B_Athena_BuriedChest_Spawner_Parent_C.SpawnChest
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Class_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FTransform                       SpawnTransform                                         (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)

void AB_Athena_BuriedChest_Spawner_Parent_C::SpawnChest(class UClass* Class_0, const struct FTransform& SpawnTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_BuriedChest_Spawner_Parent_C", "SpawnChest");

	Params::B_Athena_BuriedChest_Spawner_Parent_C_SpawnChest Parms{};

	Parms.Class_0 = Class_0;
	Parms.SpawnTransform = std::move(SpawnTransform);

	UObject::ProcessEvent(Func, &Parms);
}

}

