#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LocalPlayerMannequin_Lobby

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_LocalPlayerMannequin_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LocalPlayerMannequin_Lobby.BP_LocalPlayerMannequin_Lobby_C
// 0x0010 (0x05A8 - 0x0598)
class ABP_LocalPlayerMannequin_Lobby_C final : public ABP_LocalPlayerMannequin_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_LocalPlayerMannequin_Lobby_C;    // 0x0598(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         RetryDuration;                                     // 0x05A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_LocalPlayerMannequin_Lobby(int32 EntryPoint);
	void RetryFindingLocalPlayerCosmetics();
	void ReceiveBeginPlay();
	void CacheLocalPlayerCosmetics(bool* bFoundCosmeticsToCache);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LocalPlayerMannequin_Lobby_C">();
	}
	static class ABP_LocalPlayerMannequin_Lobby_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LocalPlayerMannequin_Lobby_C>();
	}
};
static_assert(alignof(ABP_LocalPlayerMannequin_Lobby_C) == 0x000008, "Wrong alignment on ABP_LocalPlayerMannequin_Lobby_C");
static_assert(sizeof(ABP_LocalPlayerMannequin_Lobby_C) == 0x0005A8, "Wrong size on ABP_LocalPlayerMannequin_Lobby_C");
static_assert(offsetof(ABP_LocalPlayerMannequin_Lobby_C, UberGraphFrame_BP_LocalPlayerMannequin_Lobby_C) == 0x000598, "Member 'ABP_LocalPlayerMannequin_Lobby_C::UberGraphFrame_BP_LocalPlayerMannequin_Lobby_C' has a wrong offset!");
static_assert(offsetof(ABP_LocalPlayerMannequin_Lobby_C, RetryDuration) == 0x0005A0, "Member 'ABP_LocalPlayerMannequin_Lobby_C::RetryDuration' has a wrong offset!");

}

