#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DA_Glider_Item

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DA_Glider_Item.DA_Glider_Item_C
// 0x0028 (0x1508 - 0x14E0)
class ADA_Glider_Item_C final : public AFortCustomizableAbilityDecoTool
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x14E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTagContainer                  ErrorReason;                                       // 0x14E8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_DA_Glider_Item(int32 EntryPoint);
	void BPPressTrigger(class AFortDecoHelper* FortDecoHelper);
	void RaiseUsageError(const struct FGameplayTagContainer& FailedReason);
	void IsOnGround(bool* bOnGround);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DA_Glider_Item_C">();
	}
	static class ADA_Glider_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADA_Glider_Item_C>();
	}
};
static_assert(alignof(ADA_Glider_Item_C) == 0x000008, "Wrong alignment on ADA_Glider_Item_C");
static_assert(sizeof(ADA_Glider_Item_C) == 0x001508, "Wrong size on ADA_Glider_Item_C");
static_assert(offsetof(ADA_Glider_Item_C, UberGraphFrame) == 0x0014E0, "Member 'ADA_Glider_Item_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ADA_Glider_Item_C, ErrorReason) == 0x0014E8, "Member 'ADA_Glider_Item_C::ErrorReason' has a wrong offset!");

}

