#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItempShopSection

#include "Basic.hpp"

#include "ItempShopSection_classes.hpp"
#include "ItempShopSection_parameters.hpp"


namespace SDK
{

// Function ItempShopSection.ItempShopSection_C.ExecuteUbergraph_ItempShopSection
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItempShopSection_C::ExecuteUbergraph_ItempShopSection(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItempShopSection_C", "ExecuteUbergraph_ItempShopSection");

	Params::ItempShopSection_C_ExecuteUbergraph_ItempShopSection Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItempShopSection.ItempShopSection_C.OnSelectedStateUpdated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsInSelectedState                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UItempShopSection_C::OnSelectedStateUpdated(bool bIsInSelectedState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItempShopSection_C", "OnSelectedStateUpdated");

	Params::ItempShopSection_C_OnSelectedStateUpdated Parms{};

	Parms.bIsInSelectedState = bIsInSelectedState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ItempShopSection.ItempShopSection_C.HandleFadeOutInfoAnim
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActive                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UItempShopSection_C::HandleFadeOutInfoAnim(bool IsActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ItempShopSection_C", "HandleFadeOutInfoAnim");

	Params::ItempShopSection_C_HandleFadeOutInfoAnim Parms{};

	Parms.IsActive = IsActive;

	UObject::ProcessEvent(Func, &Parms);
}

}

