#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tree_Apollo_Swamp_Tree_Large

#include "Basic.hpp"

#include "Parent_Tree_Apollo_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tree_Apollo_Swamp_Tree_Large.Tree_Apollo_Swamp_Tree_Large_C
// 0x0008 (0x0D78 - 0x0D70)
class ATree_Apollo_Swamp_Tree_Large_C final : public AParent_Tree_Apollo_C
{
public:
	class UShadowProxyMeshComponent_C*            ShadowProxyMeshComponent;                          // 0x0D70(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Tree_Apollo_Swamp_Tree_Large_C">();
	}
	static class ATree_Apollo_Swamp_Tree_Large_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATree_Apollo_Swamp_Tree_Large_C>();
	}
};
static_assert(alignof(ATree_Apollo_Swamp_Tree_Large_C) == 0x000008, "Wrong alignment on ATree_Apollo_Swamp_Tree_Large_C");
static_assert(sizeof(ATree_Apollo_Swamp_Tree_Large_C) == 0x000D78, "Wrong size on ATree_Apollo_Swamp_Tree_Large_C");
static_assert(offsetof(ATree_Apollo_Swamp_Tree_Large_C, ShadowProxyMeshComponent) == 0x000D70, "Member 'ATree_Apollo_Swamp_Tree_Large_C::ShadowProxyMeshComponent' has a wrong offset!");

}

