#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UEKittWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UEKittWidget.UEKittWidget_C
// 0x0008 (0x0410 - 0x0408)
class UUEKittWidget_C final : public UFortUEKittWidget
{
public:
	class UImage*                                 Image_40;                                          // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UEKittWidget_C">();
	}
	static class UUEKittWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUEKittWidget_C>();
	}
};
static_assert(alignof(UUEKittWidget_C) == 0x000008, "Wrong alignment on UUEKittWidget_C");
static_assert(sizeof(UUEKittWidget_C) == 0x000410, "Wrong size on UUEKittWidget_C");
static_assert(offsetof(UUEKittWidget_C, Image_40) == 0x000408, "Member 'UUEKittWidget_C::Image_40' has a wrong offset!");

}

