#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ValetModsRuntime

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


namespace SDK
{

// ScriptStruct ValetModsRuntime.ModInteractCategory
// 0x0018 (0x0018 - 0x0000)
struct FModInteractCategory final
{
public:
	struct FGameplayTag                           CategoryTag;                                       // 0x0000(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           InteractSockets;                                   // 0x0008(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(FModInteractCategory) == 0x000008, "Wrong alignment on FModInteractCategory");
static_assert(sizeof(FModInteractCategory) == 0x000018, "Wrong size on FModInteractCategory");
static_assert(offsetof(FModInteractCategory, CategoryTag) == 0x000000, "Member 'FModInteractCategory::CategoryTag' has a wrong offset!");
static_assert(offsetof(FModInteractCategory, InteractSockets) == 0x000008, "Member 'FModInteractCategory::InteractSockets' has a wrong offset!");

}

